pool:
  vmImage: 'Ubuntu-16.04'
  demands:
    - npm

<<<<<<< HEAD
steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK 2.1.505'
  inputs:
    version: 2.1.505
=======
variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '2.1.505'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'
>>>>>>> 5938c7cfc62d8a54ecd78049e3df63f6d7cf24a1

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

<<<<<<< HEAD
- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
=======
- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
>>>>>>> 5938c7cfc62d8a54ecd78049e3df63f6d7cf24a1
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
<<<<<<< HEAD
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot
=======
  workingDirectory: $(wwwrootDir)
>>>>>>> 5938c7cfc62d8a54ecd78049e3df63f6d7cf24a1

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
<<<<<<< HEAD
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - Release'
=======
  displayName: 'Build the project - $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - $(buildConfiguration)'
>>>>>>> 5938c7cfc62d8a54ecd78049e3df63f6d7cf24a1
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
<<<<<<< HEAD
    arguments: '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/Release'
=======
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
>>>>>>> 5938c7cfc62d8a54ecd78049e3df63f6d7cf24a1
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()